# Generated by Django 5.2.7 on 2025-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cpf_cnpj", models.CharField(max_length=18, unique=True)),
                ("senha", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
